name: flutter_virtual_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  cloud_firestore: ^4.13.0
  firebase_analytics: ^10.6.4
  firebase_messaging: ^14.7.4
  transparent_image: ^2.0.1
  scoped_model: ^2.0.0
  path_provider: ^2.1.1
  firebase_auth: ^4.13.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
